{
	["OptHREN"] = "",
	["OptMWHL"] = "ctrl",
	["OptDDCL"] = "desktopdecal_COS2",
	["OptCTSH"] = "off",
	["OptSHPW"] = "on",
	["OptTBOX"] = "on",
	["OptHRHV"] = "",
	["OptHRDD"] = "",
	["OptHRST"] = "on",
	["OptINIT"] = "on",
	["OptTFAC"] = "off",
	["OptMIID"] = "on",
	["OptHRNH"] = "random",
	["OptNPCD"] = "off",
	["OptTNPCH"] = "bar",
	["OptRSHE"] = "on",
	["OptTPCE"] = "on",
	["setup"] = true,
	["OptTPCH"] = "dot",
	["OptNNPC"] = "append",
	["OptMANUALROLL"] = "off",
	["OptRING"] = "on",
	["OptIMID"] = "on",
	["sidebar"] = "charsheet,note,image,table,story,quest,npc,battle,item,treasureparcel",
}