{
	["OptHRFC"] = "fumble",
	["OptSHNPC"] = "status",
	["OptHREN"] = "",
	["OptHRST"] = "off",
	["OptDDCL"] = "desktopdecal_LMOP",
	["OptSHPW"] = "on",
	["OptTBOX"] = "on",
	["OptREVL"] = "off",
	["OptRSHE"] = "on",
	["sidebar"] = "charsheet,note,image,table,story,quest,npc,battle,item,treasureparcel",
	["OptHRNH"] = "random",
	["OptNPCD"] = "off",
	["OptRNDS"] = "on",
	["OptHRHV"] = "",
	["OptINIT"] = "on",
	["OptTPCE"] = "on",
	["OptCTAV"] = "on",
	["OptWNDC"] = "off",
	["OptSHRR"] = "on",
	["OptRING"] = "on",
	["OptSHPC"] = "detailed",
	["OptHRIS"] = "",
}